// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsluytamolyjsuuymdxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzbHV5dGFtb2x5anN1dXltZHhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5NjQxOTAsImV4cCI6MjA4NzU0MDE5MH0.W7tWgu8C9YseZbw1vuRRk2YKiw_zncV99apx3Rlq4j4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});